<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generator" nsURI="hu.bme.mit.inf.critlab.codegen.dfd.generator"
    nsPrefix="hu.bme.mit.inf.critlab.codegen.dfd.generator">
  <eClassifiers xsi:type="ecore:EClass" name="PIDGenerator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetDFD" lowerBound="1"
        eType="ecore:EClass dfd_pid.ecore#//DataflowDiagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetProjectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetPackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
